development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:9567bd641be7ab1317bbb58ff5355720@scat.redistogo.com:10648/
  channel_prefix: chat_app_production
