# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000